services:
  - type: web
    name: shortlist-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: "8080"
      - key: PYTHONUNBUFFERED
        value: "1"
